### ISSUE TITLE
UPDATES LANGUAGE BR BRASIL PORTUGUÊS

### ISSUE THREAD

**Issue by MurilotiagoTI** [DokusCore/DokusCore#6]
[UPDATES LANGUAGE BR BRASIL PORTUGUÊS.md](https://github.com/DokusCore/DokusCore/files/12579192/UPDATES.LANGUAGE.BR.BRASIL.PORTUGUES.md)

**Comment by DevDokus** [comment]
Haha you made a issue post instead of a pull request ^^
But ill add it in for ya.
